### ISSUE TITLE
Provide a Zeebe example that works with Camunda cloud

### ISSUE THREAD

**Issue by OlivierAlbertini** [VilledeMontreal/workit#162]
In the `examples` folder, we should add an example on how to connect workit with Camunda Cloud
It should be done after #161  is merged

**Comment by jwulf** [comment]
I see that #61 got merged two days ago. Do you need any help with this issue?

**Comment by OlivierAlbertini** [comment]
I have already some codes working with Camunda Cloud. I think I can make the PR this week and I will put you reviewer, WDYT ?

**Comment by jwulf** [comment]
Sounds good. Happy to review it.
