### ISSUE TITLE
Make compatibility with zeebe-node 0.22.1 (BREAKING CHANGE)

### ISSUE THREAD

**Issue by OlivierAlbertini** [VilledeMontreal/workit#82]
## 🚀 Feature Proposal
we are compatible with 0.20.1.
0.20.2 brings breaking changes see https://github.com/creditsenseau/zeebe-client-node-js/commit/04be3470d832addde326dd8286e5bb9beb3fae17

**Comment by jwulf** [comment]
What's the breaking change for you?

**Comment by OlivierAlbertini** [comment]
> What's the breaking change for you?

Hi Josh,

zeebe-node accepts `OperationOptions` instead of `number` (version)

**Comment by jwulf** [comment]
Uh-huh. Something else to note: 0.20.6 removes `complete()`, you need to use `complete.success()` now.

**Comment by OlivierAlbertini** [comment]
> Uh-huh. Something else to note: 0.20.6 removes `complete()`, you need to use `complete.success()` now.

Thanks Josh!
